version: "3.9"
services:
    hello-1:
        container_name: hello-1
        image: line-hello-1:0.0.1
        restart: on-failure
        depends_on:
            - redis
        environment:
            - port=6379
            - host=redis
        ports:
            - "8000:8000"
        networks:
            - sre-net
    hello-2:
        container_name: hello-2
        image: line-hello-2:0.0.1
        restart: on-failure
        ports:
            - "8001:8000"
        networks:
            - sre-net
    redis:
        container_name: redis
        image: redis:6.2.3-buster
        restart: on-failure
        expose:
            - "6379"
        networks:
            - sre-net

networks:
    sre-net:
        driver: bridge